CREATE TABLE rooms (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(20),
  CONSTRAINT pk_id PRIMARY KEY(id));

CREATE TABLE offers (
  id INT NOT NULL AUTO_INCREMENT,
  room_id INT NOT NULL,
  contents VARCHAR(1000),
  CONSTRAINT pk_id PRIMARY KEY(id),
  CONSTRAINT fk_room_id FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE);

